### ISSUE TITLE
Integrate Algolia Autocomplete widget in WebHelp transformation

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-search-service-publishing-template#28]
Integrate Algolia Autocomplete widget in WebHelp transformation.

For the begining, I want to install the widget in the WebHelp topic page:

![image](https://user-images.githubusercontent.com/6837947/182323554-ee3e6a16-17f0-47d5-ba5e-243e69ced370.png)

See Algolia Autocomplete guide:
https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/

**Comment by radu-pisoi** [comment]
Add a topic _How to integrate Algolia autocomplete widget_ topic in documentation in Documentation phase.

**Comment by Yashmerino** [comment]
Add a topic about how to integrate Algolia autocomplete into Webhelp.
