### ISSUE TITLE
Learn Javascript ES6 standard

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-search-service-publishing-template#30]
Beni, ai putea sa-i recomanzi lui Artion cateva resurse pentru Javascript ES6.

**Comment by BeniaminSavu** [comment]
Eu cand am inceput sa ma uit peste ES6 initial am vazut aici noile feature-uri adaugate in ES6 (explicate sumar): https://www.w3schools.com/Js/js_es6.asp

Apoi eu unul de multe ori cand am nelamuriri ma uit pe site-ul de la mdn. In functie de ce ai nevoie poti gasi mai multe explicatii aici: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide
