### ISSUE TITLE
Learn how to build a JS ES6 project with Webpack

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-search-service-publishing-template#31]
Beni, ai putea sa-i recomanzi lui Artion cateva resurse pentru cum se face build-ul resurselor JS ES6 cu Webpack.

**Comment by BeniaminSavu** [comment]
Documentatia Webpack-ul o gasesti aici: https://webpack.js.org/concepts/
Din ce vad au un ghid pentru getting started cu webpack: https://webpack.js.org/guides/getting-started/
