### ISSUE TITLE
Create a React application to implement search page

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-search-service-publishing-template#40]
Create a React application to implement search page.

![image](https://user-images.githubusercontent.com/6837947/183040800-3c08611f-c7e9-4626-9838-e5b56605f73a.png)

**Comment by Yashmerino** [comment]
https://drive.google.com/file/d/1CthyXdgyxtkMt1Js0vh_3t61JtHWfYTO/view?usp=sharing
